import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const tooling = createRequire(process.argv[2]);
const { JSDOM } = tooling('jsdom');
const dom = new JSDOM('<!doctype html><html><body><main></main></body></html>', { url: 'http://localhost', pretendToBeVisual: true });
for (const key of ['window','document','navigator','HTMLElement','HTMLButtonElement','Element','Node','Text','Comment','Event','MouseEvent','KeyboardEvent','MutationObserver','getComputedStyle'])
  Object.defineProperty(globalThis, key, { configurable: true, value: dom.window[key] });
globalThis.requestAnimationFrame = dom.window.requestAnimationFrame.bind(dom.window);
globalThis.cancelAnimationFrame = dom.window.cancelAnimationFrame.bind(dom.window);
const { mount, flushSync, unmount } = await import('svelte');
const { default: Consumer } = await import('./DOMConsumer.svelte');
const target = document.querySelector('main');
const app = mount(Consumer, { target }); flushSync();
const initial = app.snapshot();
assert.equal(initial.root, target.querySelector('#packed-root'));
assert.equal(initial.trigger, target.querySelector('#packed-trigger'));
assert.equal(initial.panel, target.querySelector('#packed-panel'));
assert.equal(initial.trigger.tagName, 'SPAN'); assert.equal(initial.trigger.getAttribute('role'), 'button');
assert.equal(initial.panel.getAttribute('hidden'), 'until-found'); assert.equal(initial.panel.style.color, 'red');
assert.equal(initial.trigger.className, 'trigger'); assert.equal(initial.trigger.style.opacity, '0.5');
initial.trigger.click(); flushSync();
assert.deepEqual(app.snapshot().calls, ['consumer','change:true:false']);
assert.equal(initial.trigger.getAttribute('aria-expanded'), 'false');
initial.trigger.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true })); flushSync();
assert.deepEqual(app.snapshot().calls.slice(-2), ['consumer','change:true:false']);
assert.equal(initial.trigger.getAttribute('aria-expanded'), 'true');
assert.equal(initial.trigger.className, 'trigger open'); assert.equal(initial.trigger.style.opacity, '1');
assert.equal(initial.trigger.getAttribute('aria-controls'), 'packed-panel');
app.replace(); flushSync();
const next = app.snapshot().panel;
assert.notEqual(next, initial.panel); assert.equal(next.tagName, 'SECTION');
assert.equal(initial.panel.isConnected, false); assert.equal(next.isConnected, true);
assert(app.snapshot().attachments.some(entry => entry.host === initial.panel && !entry.attached));
assert(app.snapshot().attachments.some(entry => entry.host === next && entry.attached));
app.remove(); flushSync();
assert.equal(target.childElementCount, 0);
assert.equal(app.snapshot().root, null); assert.equal(app.snapshot().trigger, null); assert.equal(app.snapshot().panel, null);
assert(app.snapshot().attachments.some(entry => entry.host === initial.trigger && !entry.attached));
assert(app.snapshot().attachments.some(entry => entry.host === next && !entry.attached));
await unmount(app); dom.window.close();
console.log('Installed public Collapsible DOM refs/snippets/attachments, native events, cancellation and replacement cleanup: PASS');
