<script lang="ts">
  import { onMount } from 'svelte';
  import Fixture from '../../lib/DirectionProviderFixture.svelte';
  let { data } = $props();
  let host = $state<HTMLDivElement>();
  onMount(() => {
    if (!data.reference || !host) return;
    const node = host; let stopped = false; let cleanup: (() => void) | undefined;
    void import('../../lib/direction-provider-reference.js').then(({ hydrateDirectionProviderReference }) => {
      if (!stopped) cleanup = hydrateDirectionProviderReference(node, data.scenario);
    });
    return () => { stopped = true; cleanup?.(); };
  });
</script>

<!-- eslint-disable-next-line svelte/no-at-html-tags -- Trusted React fixture generated by renderToString on the server. -->
{#if data.reference}<div bind:this={host}>{@html data.html}</div>{:else}<Fixture scenario={data.scenario} />{/if}
