// Actual used Slider runtime/type closure; immutable original graph remains separate.
import ts from '../../packages/base/node_modules/typescript/lib/typescript.js';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,relative,dirname} from 'node:path';
import {createHash} from 'node:crypto';
const root=resolve(import.meta.dirname,'../..');
const entries=['packages/base/src/lib/slider/index.ts'];
const queue=entries.map(local=>({local,kind:'runtime'})),records=new Map();
function resolveImport(file,specifier){if(specifier.startsWith('@sveltery/utils/')){const suffix=specifier.slice('@sveltery/utils/'.length);const base=resolve(root,'packages/utils/src/lib',suffix);for(const candidate of [base+'.ts',base+'.svelte.ts',base+'/index.ts'])if(existsSync(candidate))return relative(root,candidate);throw new Error(`Unresolved canonical Utils ${specifier}`);}if(!specifier.startsWith('.'))return `external:${specifier}`;const base=resolve(root,dirname(file),specifier);for(const candidate of [base,base.replace(/\.js$/,'.ts'),base.replace(/\.js$/,'.svelte.ts'),base+'.ts',base+'.svelte',base+'/index.ts'])if(existsSync(candidate))return relative(root,candidate);throw new Error(`Unresolved ${file} → ${specifier}`);}
while(queue.length){const{local,kind}=queue.shift();let record=records.get(local);if(!record){const text=readFileSync(resolve(root,local),'utf8'),code=local.endsWith('.svelte')?[...text.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(match=>match[1]).join('\n'):text;
const ast=ts.createSourceFile(local,code,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),imports=[],declarations=[];
function edge(specifier,kind,names=[]){imports.push({specifier,kind,names,resolved:resolveImport(local,specifier)});}
function visit(node){if(ts.isImportDeclaration(node)&&ts.isStringLiteral(node.moduleSpecifier)){const clause=node.importClause,runtime=[],types=[];if(clause?.name)(clause.isTypeOnly?types:runtime).push(clause.name.text);if(clause?.namedBindings&&ts.isNamespaceImport(clause.namedBindings))(clause.isTypeOnly?types:runtime).push(clause.namedBindings.name.text);if(clause?.namedBindings&&ts.isNamedImports(clause.namedBindings))for(const name of clause.namedBindings.elements)(clause.isTypeOnly||name.isTypeOnly?types:runtime).push((name.propertyName??name.name).text);if(runtime.length||!clause)edge(node.moduleSpecifier.text,'runtime',runtime);if(types.length)edge(node.moduleSpecifier.text,'type',types);}else if(ts.isExportDeclaration(node)&&node.moduleSpecifier&&ts.isStringLiteral(node.moduleSpecifier))edge(node.moduleSpecifier.text,node.isTypeOnly?'type':'runtime');else if(ts.isImportTypeNode(node)&&ts.isLiteralTypeNode(node.argument)&&ts.isStringLiteral(node.argument.literal))edge(node.argument.literal.text,'type');if((ts.isFunctionDeclaration(node)||ts.isInterfaceDeclaration(node)||ts.isTypeAliasDeclaration(node)||ts.isModuleDeclaration(node))&&node.name)declarations.push(node.name.text);ts.forEachChild(node,visit);}visit(ast);record={local,sha256:createHash('sha256').update(text).digest('hex'),reachability:[],declarations,imports};records.set(local,record);}if(record.reachability.includes(kind))continue;record.reachability.push(kind);for(const edge of record.imports)if(!edge.resolved.startsWith('external:'))queue.push({local:edge.resolved,kind:kind==='type'||edge.kind==='type'?'type':'runtime'});}
const graph={pin:'47b40521eab921c2756bf9bdb0b0f07fbfdb8c8c',status:'actual used closure; Source/native/maintainability review pending',entries,modules:[...records.values()].sort((a,b)=>a.local.localeCompare(b.local))};
const output=JSON.stringify(graph,null,2)+'\n',destination=resolve(import.meta.dirname,'actual-local-graph.json');
if(process.argv.includes('--check')){if(readFileSync(destination,'utf8')!==output)throw new Error('Slider actual-local graph stale');}else writeFileSync(destination,output);
console.log(`${records.size} actual Slider runtime/type modules`);
